<?php

/**
 * @file
 * AAACN V2 theme file.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
// function aaacnv3_theme_suggestions_paragraph_alter(&$suggestions, $variables) {
//   $paragraph = $variables['elements']['#paragraph'];
//   $suggestions[] = 'xxparagraph__' . $paragraph->bundle() . '__' . $paragraph->view_mode;
//   $parent = $paragraph->getParentEntity();
//   if ($parent) {
//     $suggestions[] = 'xxparagraph__' . $parent->bundle() . '__' . $paragraph->bundle();
//   }
// }


/**
 * Implements hook_theme_suggestions_page_alter().
 */
function aaacnv3_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
	$suggestions[] = 'page__' . $node->bundle();
  }
}


function aaacnv3_theme_suggestions_field_alter(array &$suggestions, array $variables) { 
  $object = $variables['element']['#object'];
//   $suggestions[] = 'ZZZ ' . get_class($object) . '----' . $object->id() . '--'; 
  if (get_class($object) == 'Drupal\paragraphs\Entity\Paragraph') { 
    if ($variables['element']['#field_name'] == 'field_html') {
//kint($variables['element']['#field_type']);
    //if (in_array('field__body', $suggestions)) { 
      $suggestions[] = 'field__html__' . $object->field_id->value; 
    //} 
    }
  } 
}


function aaacnv3_preprocess_html(&$variables) {
  // Add node ID to the body class.
  $node = \Drupal::routeMatch()->getParameter('node');
  if (is_object($node)) {
    $variables['attributes']['class'][] = 'node-' . $node->id();
  }
}


function aaacnv3_preprocess_paragraph(&$variables) {
  $menu_link_manager = \Drupal::service('plugin.manager.menu.link');
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  $route_parameters = $route_match->getRawParameters()->all();
  $menu_links = $menu_link_manager->loadLinksByRoute($route_name, $route_parameters);
  

  
  if (!empty($menu_links)) {
    $menu_link = reset($menu_links);
    $variables['debug'] = $menu_link;
    if ($parent = $menu_link->getParent()) {
      $parent = $menu_link_manager->createInstance($parent);
      $parent_title = $parent->getTitle();
      $parent_url = $parent->getUrlObject()->toString();
      
      $variables['menu_parent_title'] = 't' . $parent_title;
      $variables['menu_parent_url'] = $parent_url;
    }
  }
}
